name: whisper-cuda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - ffmpeg
  - scipy
  - pip
  - pip:
      - -r requirements-cuda.txt
variables:
  CT2_CUDA_ALLOCATOR: cub_caching

